// <auto-generated />
using System;
using ConsoleApp.MySQL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleApp.MySQL.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20181213080824_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("ConsoleApp.MySQL.Models.DataLog", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<byte[], byte[]>(v => default(byte[]), v => default(byte[]), new ConverterMappingHints(size: 16)));

                    b.Property<DateTime>("CreateTime");

                    b.Property<short>("IsDisable")
                        .HasColumnType("bit");

                    b.Property<string>("Remark");

                    b.Property<string>("Type")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.ToTable("DataLog");

                    b.HasAnnotation("MySQL:Charset", "utf8");
                });
#pragma warning restore 612, 618
        }
    }
}
